---
# tasks file for create_user
- name: Add ec2-user to docker group
  ansible.builtin.user:
    name: ec2-user
    groups: docker
    append: yes

- name: Reconnect to server session
  meta: reset_connection
