apiVersion: v1
kind: Service
metadata:
  name: phpfpm
  labels:
    app: phpfpm
spec:
  ports:
    - protocol  : TCP
      port      : 9000
      targetPort: 9000
  selector:
    app: phpfpm

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  ports:
    - protocol  : TCP
      port      : 8080
      targetPort: 8080
  selector:
    app: nginx
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - protocol  : TCP
      port      : 3306
      targetPort: 3306
  selector:
    app: mysql
