apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-env
data:
  MYSQL_DATABASE: "test_db"
  MYSQL_ROOT_PASSWORD: "123456"
  MYSQL_PASSWORD: "1234567"
  MYSQL_USER: "test_user"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
    app: mysql
spec:
  serviceName: mysql
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
      - name: db-disk
        persistentVolumeClaim:
           claimName: db-disk-pvc
      containers:
      - name: mysql
        image: mysql:latest
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: mysql-env
        volumeMounts:
        - name: db-disk
          mountPath: /var/lib/mysql/
