apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-2g
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-3
spec:
  volumes:
    - name: google-disk
      persistentVolumeClaim:
        claimName: pvc-2g
  containers:
    - name: nginx-3
      image: nginx:1.14.2
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: google-disk
