apiVersion: v1
kind: Pod
metadata:
  name: nginx-2
spec:
  volumes:
    - name: google-disk
      persistentVolumeClaim:
        claimName: pvc-1g
  containers:
    - name: nginx-2
      image: nginx:1.14.2
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: google-disk
