#!/usr/bin/env groovy

pipeline {
  agent any

  stages {

    stage('Destroy server on AWS') {
      environment {
        AWS_ACCESS_KEY_ID = credentials('aws_access_key_id')
        AWS_SECRET_ACCESS_KEY = credentials('aws_secret_access_key')
      }

      steps {
        script {
          dir ('/var/lib/jenkins/workspace/aws_create-instance_and_deploy-app/terraform_learning/aws_jenkins') {
            sh "terraform destroy -auto-approve"
          }
        }
      }
    }
  }
}
