my_region         = "us-east-2"
avail_zone        = "us-east-2a"
vpc_cidr_block    = "10.0.0.0/16"
subnet_cidr_block = "10.0.1.0/24"
env_prefix        = "dev"
instance_type     = "t2.micro"
my_whitelist      = ["95.167.217.2/32", "37.23.63.0/24"]
public_key_name   = "server-1" # ssh key on aws
# public_key_location = "/home/maxim/.ssh/id_rsa.pub"
private_key_location = "/home/maxim/devops/keys_for_ssh/server-1.pem"
