---
- name: Install java and net-tools
  # become: yes
  hosts: lnd1

  tasks:

  - name: Update apt repo and cache
    apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  - name: Install pckgs
    apt:
      pkg:
        - openjdk-8-jre-headless
        - net-tools
        - acl

  - name: Check nexus folder stats
    stat:
      path: /opt/nexus
    register: stat_result

  - name: Download Nexus
    get_url:
      url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
      dest: /opt/
    register: download_result
    when: not stat_result.stat.exists

  - name: Untar nexus installer
    unarchive:
      src: "{{ download_result.dest }}"
      dest: /opt/
      remote_src: yes
    when: not stat_result.stat.exists

  - name: Find Nexus folder
    find:
      paths: /opt
      pattern: "nexus-*"
      file_type: directory
    register: find_result

  - name: Rename nexus folder
    shell: mv {{ find_result.files[0].path }} /opt/nexus
    when: not stat_result.stat.exists

  - name: Ensure group exists
    group:
      name: nexus
      state: present

  - name: Create nexus user
    user:
      name: nexus
      group: nexus

  - name: Make nexus user owner of nexus folder
    file:
      path: /opt/nexus
      state: directory
      owner: nexus
      group: nexus
      recurse: yes

  - name: Make sonatype-work user owner of nexus folder
    file:
      path: /opt/sonatype-work
      state: directory
      owner: nexus
      group: nexus
      recurse: yes

- name: Install java and net-tools
  become: yes
  become_user: nexus
  hosts: lnd1

  tasks:

  - name: Set run_as_user nexus
    lineinfile:
      path: /opt/nexus/bin/nexus.rc
      regexp: '^#run_as_user=""'
      line: run_as_user="nexus"

  - name: Start nexus
    command: /opt/nexus/bin/nexus start

  - name: Ensure nexus is running
    shell: ps aux | grep nexus
    register: nexus_status
  - debug: msg={{ nexus_status.stdout_lines }}

  - name: Wait for port 8081 to become open on the host
    wait_for:
      port: 8081
      delay: 10
      connect_timeout: 60

  - name: Check with netstat
    shell: netstat -lnpt
    register: netstat_status
  - debug: msg={{ netstat_status.stdout_lines }}
