version: '3.7'
services:
  my-app:
    image: tmax23/js-app:latest
    restart: unless-stopped
    ports:
     - 80:3000
    networks:
      - mynet
  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
     - mongo-data:/data/db
    networks:
      - mynet
  mongo-express:
    image: mongo-express
    depends_on:
      - mongodb
    container_name: mongo-express
    restart: unless-stopped
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
    networks:
      - mynet
volumes:
  mongo-data:
    driver: local
networks:
  mynet:
    driver: bridge
