apiVersion: v1
kind: Service
metadata:
  name: php-fpm
  labels:
    run: php-fpm
spec:
  ports:
    - protocol  : TCP
      port      : 9000
  selector:
    run: php-fpm
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    run: nginx
spec:
  ports:
    - protocol  : TCP
      port      : 80
  selector:
    run: nginx
  type: LoadBalancer
