apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-volume
  annotations:
    pv.kubernetes.io/provisioned-by: ebs.csi.aws.com
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard-rwo
  claimRef:
    name: my-pvc
    namespace: default
  csi:
    driver: ebs.csi.aws.com
    volumeHandle: vol-042c9fc47ae64d7c1
    fsType: ext4
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: topology.ebs.csi.aws.com/zone
  #         operator: In
  #         values:
  #         - us-east-2a

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: standard-rwo
  volumeName: aws-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi

---
apiVersion: v1
kind: Pod
metadata:
  name: http-server
spec:
  containers:
  - image: bakavets/kuber
    name: http-server
    volumeMounts:
    - mountPath: /cache
      name: data
  volumes:
  - name: data
    persistentVolumeClaim:
       claimName: my-pvc

    # # This AWS EBS volume must already exist.
    # awsElasticBlockStore:
    #   volumeID: "vol-042c9fc47ae64d7c1"
    #   fsType: ext4
