def gv

pipeline {
    agent any

    tools {
       maven 'maven-3.8.3'
    }

    parameters {
      choice ( name: 'VERSION', choices: ['1.0.0', '1.0.1', '1.1.0'], description: 'versions of app' )
      booleanParam ( name: 'executeTests', defaultValue: true, description: 'nota bene' )
    }
    environment {
      NEW_VERSION = "1.1.0"
      SERVER_CREDENTIALS = credentials('test-user-id')
    }
    stages {
      stage('init'){
        steps {
          script{
             gv = load "script.groovy"
          }

        }

      }

      stage('build') {
        steps {
            script {
              gv.buildApp()
              gv.testApp()
            }

            }
      }

      stage('test') {
        when {
          expression {
            params.executeTests == true
          }
        }
            steps {
              script {
                gv.testApp()
              }
            }
      }

      stage('deploy') {
            steps {
              script {
                gv.deployApp()
              }
                    }
            }
      }





    }
