pipeline {
    agent any

    stages {

        stage('Test app') {
            steps {
                echo "Testing app"
                echo "Current branch is $BRANCH_NAME"
            }
        }

        stage('Build app') {
            when {
               expression {
               BRANCH_NAME == 'jenkins-jobs'
                }
            }

            steps {
              echo "Building app"
            }

        }

        stage('Deploy app') {

          when {
             expression {
             BRANCH_NAME == 'jenkins-jobs'
             }
          }
            steps {
              echo "Deploying app"
              }

        }
    }
}
