#!/usr/bin/env groovy

@Library('jenkins-shared-library')_

pipeline {
    agent any
    tools {
        maven 'maven-3.6.3'
    }

    stages {

      stage('build app') {
        steps {
            script {
              buildJar()
              }

            }
      }

      stage('build image') {
        steps {
            script {
              buildImage 'tmax23/java-maven-app:2.0'
              }

            }
      }

    }

}
