---
  - name: Understanding "delegate_to"
    hosts: aws-server-1
    become: yes

    tasks:

      # - name: "Reboot servers"
      #   shell: "sleep 5 && reboot now"
      #   async: 1
      #   poll: 0
      #
      # - name: "Waiting for loading OS"
      #   become: no
      #   wait_for_connection:
      #

      - name: "Uptime..."
        shell: hostname
        register: results
        delegate_to: gcp-server-1
        

      - name: "Print uptime"
        debug:
          var: results.stdout_lines
