---
- name: Deploy test APP
  hosts: "{{ HOSTS }}"
  become: yes
  any_errors_fatal: true

  roles:
       # - mysql-deploy
       # - nginx-deploy
       # - php-deploy
       - mysql-create-db
       - deploy-php-page
