---
 - name: Install apache web servers
   hosts: all
   become: yes

   tasks:
   - name: Install Apache
     apt:
       name: apache2
       state: latest
#       update_cache: yes

   - name: Start Apache and autorun
     ansible.builtin.service:
       name: apache2
       state: started
       enabled: yes
