- name: Change password MySQL from cli
  hosts: aws-redhat-3
  become: yes
  any_errors_fatal: true

  vars:
    MYSQL_PASSWORD: arlTaa!s12Ra

  tasks:
    - name: grep 'temporary password' for RedHat
      shell:
        cmd: grep 'temporary password' /var/log/mysqld.log | cut -d " " -f 13
      register: password

    - name: Set MySQL root Password for RedHat
      become: no
      shell:
        cmd: set +o histexpand
      when: ansible_os_family == "RedHat"

    - name: Set MySQL root Password for RedHat
      shell:
        cmd: mysql -u root -p"{{ password.stdout }}" --connect-expired-password -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ MYSQL_PASSWORD }}';"
      when: ansible_os_family == "RedHat"
