---
- name: Remove test APP
  hosts: "{{ HOSTS }}"
  become: yes
  any_errors_fatal: true

  tasks:
    - fail:
        msg: Unsupported version OS
      when: ( ansible_os_family == "RedHat" and ansible_distribution_major_version != "8" ) or
            ( ansible_distribution == "Debian" and ansible_distribution_major_version != "10" ) or
            ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version != "20" )

  roles:
    - role: remove-app
