- name: Test tasks
  hosts: aws-debian
  become: yes
  # any_errors_fatal: true

  tasks:
   - name: Debian - remove files
     ansible.builtin.file:
       path: /etc/apt/sources.list.d/mysql.list
       state: absent
