---

- name: Run several insert queries against db test_db in single transaction
  community.mysql.mysql_query:
    login_user: "{{ TEST_USER_NAME }}"
    login_password: "{{ TEST_USER_PASSWORD }}"
    login_db: "{{ TEST_DB_NAME }}"
    query: "{{ TABLE }}"
    single_transaction: yes
  ignore_errors: yes

- name: Run several insert queries against db test_db in single transaction
  community.mysql.mysql_query:
    login_user: "{{ TEST_USER_NAME }}"
    login_password: "{{ TEST_USER_PASSWORD }}"
    login_db: "{{ TEST_DB_NAME }}"
    query: "{{ CONTENT_FOR_TABLE }}"
    single_transaction: yes
