---
# tasks file for mysql-create-db
- name: RedHat - install python3-pip
  yum:
    name: python3-pip
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Ubuntu/Debian - install python3-pip
  apt:
    name: python3-pip
    state: latest
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: All - install PyMySQL
  pip:
    name: pymysql

- name: Redhat - create database MySQL
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_unix_socket: "{{ MYSQL_SOCKET_REDHAT }}"
    name: "{{ TEST_DB_NAME }}"
    state: present
  when: ansible_os_family == "RedHat"

- name: Ubuntu - create database MySQL
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_unix_socket: "{{ MYSQL_SOCKET_UBUNTU_DEBIAN }}"
    name: "{{ TEST_DB_NAME }}"
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Debian - create database MySQL
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ MYSQL_PASSWORD }}"
    name: "{{ TEST_DB_NAME }}"
    state: present
  when: ansible_distribution == "Debian"

- name: Redhat - create user for TEST_DB
  community.mysql.mysql_user:
    check_implicit_admin: yes
    login_unix_socket: "{{ MYSQL_SOCKET_REDHAT }}"
    name: "{{ TEST_USER_NAME }}"
    password: "{{ TEST_USER_PASSWORD }}"
    priv: '{{ TEST_DB_NAME }}.*:ALL'
    state: present
  when: ansible_os_family == "RedHat"

- name: Ubuntu - create user for TEST_DB
  community.mysql.mysql_user:
    check_implicit_admin: yes
    login_unix_socket: "{{ MYSQL_SOCKET_UBUNTU_DEBIAN }}"
    name: "{{ TEST_USER_NAME }}"
    password: "{{ TEST_USER_PASSWORD }}"
    priv: '{{ TEST_DB_NAME }}.*:ALL'
    state: present
  when: ansible_distribution == "Ubuntu"

- name: Debian - create user for TEST_DB
  community.mysql.mysql_user:
    check_implicit_admin: yes
    login_user: root
    login_password: "{{ MYSQL_PASSWORD }}"
    name: "{{ TEST_USER_NAME }}"
    password: "{{ TEST_USER_PASSWORD }}"
    priv: '{{ TEST_DB_NAME }}.*:ALL'
    state: present
  when: ansible_distribution == "Debian"

- include: create-table.yml
