#!/usr/bin/awk -f

for file in $(find . -name "*.yaml");do
awk '
  {
      for(i=1;i<=NF;i++)
        {
          j=1;
          j++;
          if($i=="control:" && $j=="const:")
            {
              print $j
            }
        }
  }'
  $file;
  done
