---
- fail:
    msg: Unsupported version OS
  when: ( ansible_os_family == "RedHat" and ansible_distribution_major_version != "8" ) or
          ( ansible_distribution == "Debian" and ansible_distribution_major_version != "10" ) or
          ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version != "20" )

#======Install NGINX for RedHat =================
- block:

  - name: RedHat - install nginx
    yum:
      name: nginx
      state: latest
      update_cache: yes

  - name: RedHat - start nginx and autorun
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

  when: ansible_os_family == "RedHat"
#================================================

#====== Install NGINX for Ubuntu/Debian ================
- block:

  - name: Ubuntu/Debian - install nginx
    apt:
      name: nginx
      state: latest
      update_cache: yes

  - name: Debian - start nginx and autorun
    service:
      name: nginx
      state: started
      enabled: yes

  when: ansible_os_family == "Debian"
#================================================
