---
- name: RedHat - remove nginx
  yum:
    name: nginx
    state: absent
  when: ansible_os_family == "RedHat"

- name: Ubuntu/Debian - remove nginx
  apt:
    name: nginx
    purge: yes
    state: absent
  when: ansible_os_family == "Debian"
