---
- name: RedHat - remove MySQL
  yum:
    name: mysql-server
    state: absent
  when: ansible_os_family == "RedHat"

#======= Begin Debian ======================
- name: Debian block - removing gnupg and apt_key
  block:

  - name: Debian - remove gnupg
    apt:
      name: gnupg
      purge: yes
      state: absent

  - name: Debian - remove an apt_key
    ansible.builtin.apt_key:
      id: 5072E1F5
      state: absent

  - name: Debian - remove mysql.list
    ansible.builtin.file:
      path: "{{ DEST_SOURCES_LIST_DEBIAN }}/mysql.list"
      state: absent

  when: ansible_distribution == "Debian"
#======= End Debian ========================

- name: Ubuntu/Debian - remove MySQL
  apt:
    name: mysql-server
    purge: yes
    state: absent
  when: ansible_os_family == "Debian"

- name: All - remove /var/lib/mysql/
  ansible.builtin.file:
    path: /var/lib/mysql/
    state: absent

- name: All - remove /var/log/mysqld.log
  ansible.builtin.file:
    path: /var/log/mysqld.log
    state: absent
