---
# =========== Begin - RedHat block: install MySQL======
- name: RedHat block - install MySQL
  block:

  - name: RedHat - install MySQL
    yum:
      name: mysql-server
      state: latest
      update_cache: yes

  - name: RedHat - start MySQL and autorun
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: RedHat - set MySQL root password
    shell:
      cmd: mysql -u root -e "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{ MYSQL_PASSWORD }}';"
    ignore_errors: yes
    
  when: ansible_os_family == "RedHat"
# =========== End - RedHat block: install MySQL========
