---
- name: Download MySQL Yum Repository for RedHat-6
  get_url:
    url: "{{ MYSQL_YUM_6_REPO }}"
    dest: /tmp/mysql80-community-release.rpm
    mode: '0664'
  when: ansible_distribution_major_version == "6"

- name: Download MySQL Yum Repository for RedHat-7
  get_url:
    url: "{{ MYSQL_YUM_7_REPO }}"
    dest: /tmp/mysql80-community-release.rpm
    mode: '0664'
  when: ansible_distribution_major_version == "7"

- name: Download MySQL Yum Repository for RedHat-8
  get_url:
    url: "{{ MYSQL_YUM_8_REPO }}"
    dest: /tmp/mysql80-community-release.rpm
    mode: '0664'
  when: ansible_distribution_major_version == "8"

- name: Install MySQL Yum Repository for RedHat
  yum:
    name: /tmp/mysql80-community-release.rpm
    state: present
  when: ansible_os_family == "RedHat"

- name: Install MySQL Yum Repository for RedHat
  yum:
    name: /tmp/mysql80-community-release.rpm
    state: present
  when: ansible_os_family == "RedHat"

- name: yum module disable mysql for RedHat-8
  shell:
    cmd: yum -y module disable mysql
  when: ansible_distribution_major_version == "8"

- name: Install MySQL for RedHat
  yum:
    name: mysql-community-server
    state: latest
    update_cache: yes
  when: ansible_os_family == "RedHat"

- name: Start MySql and autorun for RedHat
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes
  when: ansible_os_family == "RedHat"

- name: grep 'temporary password' for RedHat
  shell:
    cmd: grep 'temporary password' /var/log/mysqld.log | cut -d " " -f 13
  register: password
  when: ansible_os_family == "RedHat"

- name: Install python3 for RedHat
  yum:
    name: python3
    state: latest
  when: ansible_os_family == "RedHat"

- name: Install PyMySQL for RedHat
  shell:
    cmd: python3 -m pip install PyMySQL
  when: ansible_os_family == "RedHat"

- name: Set MySQL root Password for RedHat
  mysql_user:
    host: localhost
    login_user: root
    login_password: "{{ password.stdout }}"
    name: root
    password: "{{ MYSQL_PASSWORD }}"
    state: present
  when: ansible_os_family == "RedHat"
