---
# tasks file for mysql-deploy
- fail:
    msg: Unsupported version OS
  when: ( ansible_os_family == "RedHat" and ansible_distribution_major_version != "8" ) or
          ( ansible_distribution == "Debian" and ansible_distribution_major_version != "10" ) or
          ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version != "20" )

- include: for-ubuntu-debian.yml
- include: for-redhat.yml
