---
- name: Ubuntu/Debian - pre-configure mysql-community-server passphrase
  ansible.builtin.debconf:
    name: mysql-community-server
    question: mysql-community-server/root-pass
    value: "{{ MYSQL_PASSWORD }}"
    vtype: password
  no_log: True

- name: Ubuntu/Debian - pre-configure mysql-community-server re-passphrase
  ansible.builtin.debconf:
      name: mysql-community-server
      question: mysql-community-server/re-root-pass
      value: "{{ MYSQL_PASSWORD }}"
      vtype: password
  no_log: True
